file_format: "1"
id: poached_eggs
name: Poached Eggs
type: shield
url: https://github.com/omwegg/poached-egg-shield-module
requires: [seeed_xiao]
features:
  - keys
  - display
siblings:
  - poached_eggs_left
  - poached_eggs_right